import { Sora, DM_Sans } from "next/font/google";
import "./globals.css";
import '@mantine/core/styles.css';
import { ColorSchemeScript, MantineProvider, mantineHtmlProps } from '@mantine/core';
import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";

const sora = Sora({
  variable: "--font-sora",
  subsets: ["latin"],
  weight: ["400", "500", "600"],
});

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
  weight: ["400", "500"],
});

export const metadata = {
  title: "Phrase Pop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
      </head>
      <body className={`${sora.variable} ${dmSans.variable} antialiased`}>
        <MantineProvider>

          <main>

            <div className="blob-pink" aria-hidden="true" />
            <div className="blob-yellow" aria-hidden="true" />

            <Navbar />

            {children}

            <Footer />

          </main>

        </MantineProvider>
      </body>
    </html>
  );
}
