import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SparklesIcon from "@/components/SparklesIcon";
import Link from "next/link";
import '@mantine/core/styles.css';
import { ColorSchemeScript, MantineProvider, mantineHtmlProps } from '@mantine/core';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Phrase Pop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" {...mantineHtmlProps}>
    <head>
      <ColorSchemeScript />
    </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#5AB2FF] text-white`}
      >
      <MantineProvider>

        <main className="p-4 max-w-2xl mx-auto">

          <header className="flex justify-between my-8">
            <Link href="/" className="flex gap-1">
              <SparklesIcon/>
              <span>PhrasePop</span>
            </Link>
            <nav className="flex gap-6 text-white/80">
              <Link href="/">Home</Link>
              <Link href="/about">About</Link>
              <a href="mailto:pragyanpatidar14@gmail.com">Contact</a>
            </nav>
          </header>

          {children}

        </main>

      </MantineProvider>
      </body>
    </html>
  );
}
